services:
  - type: web
    name: plant-disease-classifier-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
      - key: MODEL_PATH
        value: "model/plant_disease_model.h5"
